In [85]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [86]:
dataset=pd.read_csv("income1.csv")

In [87]:
dataset

age   workclass   education        occupation      sex   capital-gain  \
0     39   State-gov   Bachelors      Adm-clerical     Male           2174   
1     50   State-gov   Bachelors   Exec-managerial     Male              0   
2     38     Private     HS-grad      Adm-clerical     Male              0   
3     28     Private   Bachelors   Exec-managerial   Female              0   
4     52   State-gov     HS-grad   Exec-managerial     Male              0   
5     42     Private   Bachelors   Exec-managerial     Male           5178   
6     30   State-gov   Bachelors   Exec-managerial     Male              0   
7     23     Private   Bachelors      Adm-clerical   Female              0   
8     25   State-gov     HS-grad      Adm-clerical     Male              0   
9     32     Private     HS-grad             Sales     Male              0   
10    54     Private     HS-grad      Adm-clerical   Female              0   
11    59     Private     HS-grad      Adm-clerical   Female              0   
12    19     Private     HS-grad             Sales     Male              0   
13    39     Private     HS-grad   Exec-managerial     Male              0   
14    49     Private     HS-grad             Sales     Male              0   
15    45     Private   Bachelors   Exec-managerial     Male              0   
16    19     Private     HS-grad      Adm-clerical   Female              0   
17    53   State-gov   Bachelors   Exec-managerial     Male              0   
18    24     Private   Bachelors      Adm-clerical     Male              0   
19    49     Private     HS-grad      Adm-clerical   Female              0   
20    25     Private     HS-grad      Adm-clerical     Male              0   
21    53     Private     HS-grad             Sales     Male              0   
22    44     Private     HS-grad   Exec-managerial   Female              0   
23    41   State-gov     HS-grad             Sales     Male              0   
24    29     Private     HS-grad   Exec-managerial     Male              0   
25    25     Private   Bachelors   Exec-managerial   Female              0   
26    47   State-gov     HS-grad   Exec-managerial     Male              0   
27    43     Private   Bachelors      Adm-clerical     Male              0   
28    41     Private     HS-grad      Adm-clerical     Male              0   
29    30     Private     HS-grad             Sales     Male           5013   
..   ...         ...         ...               ...      ...            ...   
340   33     Private   Bachelors             Sales     Male              0   
341   41     Private     HS-grad      Adm-clerical   Female              0   
342   20     Private   Bachelors             Sales     Male              0   
343   26     Private   Bachelors   Exec-managerial   Female              0   
344   52     Private   Bachelors      Adm-clerical     Male              0   
345   58     Private   Bachelors      Adm-clerical   Female              0   
346   25     Private   Bachelors             Sales   Female              0   
347   24     Private   Bachelors   Exec-managerial     Male              0   
348   19     Private   Bachelors   Exec-managerial     Male              0   
349   43     Private   Bachelors   Exec-managerial     Male              0   
350   39     Private     HS-grad      Adm-clerical   Female              0   
351   49     Private     HS-grad      Adm-clerical     Male              0   
352   32     Private     HS-grad             Sales     Male              0   
353   34     Private   Bachelors   Exec-managerial     Male              0   
354   28     Private     HS-grad             Sales     Male              0   
355   25     Private   Bachelors      Adm-clerical   Female              0   
356   34     Private   Bachelors   Exec-managerial     Male              0   
357   50     Private     HS-grad   Exec-managerial     Male           7688   
358   44     Private   Bachelors             Sales     Male              0   
359   28     Private   Bach

In [88]:
x=dataset.iloc[:,:-2]

In [89]:
x=dataset.iloc[:,:-2].values

In [90]:
x

array([[39, ' State-gov', ' Bachelors', ..., 2174, 0, 40],
       [50, ' State-gov', ' Bachelors', ..., 0, 0, 13],
       [38, ' Private', ' HS-grad', ..., 0, 0, 40],
       ...,
       [44, ' Private', ' Bachelors', ..., 0, 0, 40],
       [29, ' Private', ' Bachelors', ..., 0, 0, 40],
       [30, ' Private', ' Bachelors', ..., 0, 0, 40]], dtype=object)

In [91]:
dataset.isnull().any()

age                False
 workclass         False
 education         False
 occupation        False
 sex               False
 capital-gain      False
 capital-loss      False
 hours-per-week    False
 native-country    False
 income            False
dtype: bool

In [92]:
y=dataset.iloc[:,9]

In [93]:
y=dataset.iloc[:,9].values

In [94]:
y

array([' <=50K', ' <=50K', ' <=50K', ' <=50K', ' >50K', ' >50K', ' >50K',
       ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K',
       ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K',
       ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K',
       ' <=50K', ' <=50K', ' >50K', ' <=50K', ' <=50K', ' <=50K',
       ' <=50K', ' >50K', ' <=50K', ' <=50K', ' <=50K', ' >50K', ' >50K',
       ' <=50K', ' <=50K', ' >50K', ' <=50K', ' <=50K', ' <=50K',
       ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' >50K',
       ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K',
       ' >50K', ' >50K', ' >50K', ' >50K', ' <=50K', ' <=50K', ' <=50K',
       ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K',
       ' <=50K', ' <=50K', ' <=50K', ' >50K', ' <=50K', ' >50K', ' <=50K',
       ' >50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' <=50K',
       ' <=50K', ' <=50K', ' <=50K', ' <=50K', ' >50K', ' <=50K',
       ' <=50K', ' >50K', ' <=50K', ' <

In [95]:
y.shape

(370,)

In [96]:
from sklearn.preprocessing import LabelEncoder 
lb=LabelEncoder()

In [97]:
lb1=LabelEncoder()
x[:,1]=lb1.fit_transform(x[:,1])

In [98]:
x

array([[39, 1, ' Bachelors', ..., 2174, 0, 40],
       [50, 1, ' Bachelors', ..., 0, 0, 13],
       [38, 0, ' HS-grad', ..., 0, 0, 40],
       ...,
       [44, 0, ' Bachelors', ..., 0, 0, 40],
       [29, 0, ' Bachelors', ..., 0, 0, 40],
       [30, 0, ' Bachelors', ..., 0, 0, 40]], dtype=object)

In [99]:
lb2=LabelEncoder()
x[:,2]=lb2.fit_transform(x[:,2])

In [100]:
x

array([[39, 1, 0, ..., 2174, 0, 40],
       [50, 1, 0, ..., 0, 0, 13],
       [38, 0, 1, ..., 0, 0, 40],
       ...,
       [44, 0, 0, ..., 0, 0, 40],
       [29, 0, 0, ..., 0, 0, 40],
       [30, 0, 0, ..., 0, 0, 40]], dtype=object)

In [101]:
lb3=LabelEncoder()
x[:,3]=lb3.fit_transform(x[:,3])

In [102]:
x

array([[39, 1, 0, ..., 2174, 0, 40],
       [50, 1, 0, ..., 0, 0, 13],
       [38, 0, 1, ..., 0, 0, 40],
       ...,
       [44, 0, 0, ..., 0, 0, 40],
       [29, 0, 0, ..., 0, 0, 40],
       [30, 0, 0, ..., 0, 0, 40]], dtype=object)

In [103]:
lb4=LabelEncoder()
x[:,4]=lb4.fit_transform(x[:,4])

In [104]:
x

array([[39, 1, 0, ..., 2174, 0, 40],
       [50, 1, 0, ..., 0, 0, 13],
       [38, 0, 1, ..., 0, 0, 40],
       ...,
       [44, 0, 0, ..., 0, 0, 40],
       [29, 0, 0, ..., 0, 0, 40],
       [30, 0, 0, ..., 0, 0, 40]], dtype=object)

In [105]:
y=lb.fit_transform(y)

In [106]:
y

array([0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,

In [107]:
from sklearn.preprocessing import OneHotEncoder  #To simplify the binary values(numerical values)
oh=OneHotEncoder(categorical_features=[3]) #removes unwanted things
x=oh.fit_transform(x).toarray()

C:\Users\Yashu\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Yashu\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [108]:
x

array([[1.000e+00, 0.000e+00, 0.000e+00, ..., 2.174e+03, 0.000e+00,
        4.000e+01],
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        1.300e+01],
       [1.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        4.000e+01],
       ...,
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        4.000e+01],
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        4.000e+01],
       [1.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
        4.000e+01]])

In [109]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [110]:
x_train

array([[ 1.,  0.,  0., ...,  0.,  0., 35.],
       [ 1.,  0.,  0., ...,  0.,  0., 40.],
       [ 0.,  0.,  1., ...,  0.,  0., 25.],
       ...,
       [ 1.,  0.,  0., ...,  0.,  0., 40.],
       [ 1.,  0.,  0., ...,  0.,  0., 40.],
       [ 1.,  0.,  0., ...,  0.,  0., 12.]])

In [111]:
y_test

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0])

In [112]:
y_train=y_train.flatten()

In [113]:
from sklearn.ensemble import RandomForestClassifier

In [114]:
classifier=RandomForestClassifier(n_estimators=10)
classifier.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [115]:
y_pred  = classifier.predict(x_test)

In [116]:
y_pred

array([0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0])

In [117]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[52,  4],
       [ 6, 12]], dtype=int64)

In [118]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8648648648648649